<a href="https://colab.research.google.com/github/bogiereddy/machine-learning_practice/blob/main/naviebayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df =pd.read_csv('/content/emails.csv')

In [6]:
df

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [8]:
df.groupby('spam').describe()

      text
     count unique                                                top freq
spam
0     4360   4327  Subject: telephone interview with the enron re...    2
1     1368   1368  Subject: hot stock info : drgv announces anoth...    1

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df.text,df.spam, test_size=0.20, random_state=42)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()#converting text to lowercase, ignoring punctuation
X_train_count = v.fit_transform(X_train.values) # builds a vocabulary of all unique words, and converts the text into a matrix of word counts.
X_train_count.toarray()[:3]#the first 3 documents/rows.

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [20]:
emails=['research and development charges.',
        'upto 20%discount on pricing, eclusive offer just for you. dont miss this reward!'
        ]
emails_count= v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [21]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.987783595113438

In [22]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
                ('vectorizer',CountVectorizer()),
                ('nb',MultinomialNB())
])

In [23]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [24]:
clf.score(X_test,y_test)

0.987783595113438

In [25]:
clf.predict(emails)

array([0, 1])